services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # API REST
      - "6334:6334" # gRPC (opcional, si lo usas)
    volumes:
      - qdrant:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant: {}
