services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    ports:
      - "11434:11434"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 24g # puedes ajustar hasta 32g o más si quieres
          cpus: "4.0" # asigna varios núcleos, pero no todos
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia

  open-webui:
    image: ghcr.io/open-webui/open-webui:main # v0.6.5
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
      - "WEBUI_SECRET_KEY="
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # API REST
      - "6334:6334" # gRPC (opcional, si lo usas)
    volumes:
      - qdrant:/qdrant/storage
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  qdrant: {}
